/** Approved PR-J2B3A active metadata manifest — 24 active journeys. */
import type { B3aActiveManifestEntry } from './activeMetadataBackfill';

export const PR_J2B3A_ACTIVE_MANIFEST: readonly B3aActiveManifestEntry[] = [
	{
		id: '37f6a3ae-f758-4449-83f5-e036c83f189d',
		slug: "badaling-great-wall-day-tour",
		pageTitle: { proposed: "Badaling Great Wall Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Beijing begins, Beijing ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1771747900791-%E4%B8%BB%E5%9B%BE-%E5%85%AB%E8%BE%BE%E5%B2%AD%E9%95%BF%E5%9F%8E-%E6%A8%AA%E5%9B%BE-I5XJSRFtV6au0gTCTXw6TWd7UoT4fh.jpg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '3468ea14-5f5e-40f6-9234-0fedf137189e',
		slug: "beijing-city-imperial-grandeur-urban-chic-1-day-tour",
		pageTitle: { proposed: "Beijing City Imperial Grandeur & Urban Chic 1-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Navigating the Monumental Scale of Dynastic History and the Avant-Garde Ambition of a Modern Metropolis.", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1771749910450-%E4%B8%BB%E5%9B%BE-%E6%95%85%E5%AE%AB-%E6%A8%AA%E5%9B%BE-v6JynohkI6UiYbNv4kXh63fUsV6p7N.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '8f3cdc36-f243-45da-b3b5-ecfba83929a6',
		slug: "beijing-cultural-highlights-and-iconic-sights-5-multi-days-tour",
		pageTitle: { proposed: "Beijing Cultural Highlights, and Iconic Sights  5 Multi-Days Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Beijing begins, Beijing ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1766842579054-%E4%B8%BB%E5%9B%BE-%E6%A8%AA%E5%9B%BE-hjLT44tBhGSiUk0G8wk7chpW0Yu8Iy.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'd5e5c0e9-6549-497a-97a3-4843621da5dc',
		slug: "beijing-to-mutianyu-great-wall-day-tour",
		pageTitle: { proposed: "Beijing to Mutianyu Great Wall Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Beijing begins, Beijing ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1771688549942-%E4%B8%BB%E5%9B%BE-%E6%85%95%E7%94%B0%E5%B3%AA%E9%95%BF%E5%9F%8E-%E6%A8%AA%E5%9B%BE-fwCKaJ5Q0zNkoOew79SY9tN8SXCMSe.jpg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '4d3bbbb8-3907-459b-af10-181ace7af8ec',
		slug: "beijing-to-shanxi-ancient-architecture-with-black-myth-wukong-inspirations-6-day-tour",
		pageTitle: { proposed: "Beijing to Shanxi Ancient Architecture with Black Myth: Wukong Inspirations  6-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Beijing begins, Xi’an ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1766845845305-D1-%E5%A4%A7%E5%90%8C%E5%8F%A4%E5%9F%8E-%E7%AB%96%E5%9B%BE-CvfB9ls8Q7HhZavjCmqai1HKdlUgqN.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '12da1d30-0d8d-49df-b350-fe6880c56ab8',
		slug: "chaoshan-region-cultural-heritage-6-day-tour",
		pageTitle: { proposed: "Chaoshan Region Cultural Heritage 6-Day  Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Chaozhou begins, Jieyang ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767327974888-%E4%B8%BB%E5%9B%BE-%E6%BD%AE%E6%B1%95-%E6%A8%AA%E5%9B%BE-7jm5TXOGouZn5XH3Bz7nlBoG5zBjVF.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '535ac95b-f891-4e1c-916f-57028d7cb9e0',
		slug: "chengdu-chongqing-double-cities-6-day-tour",
		pageTitle: { proposed: "Chengdu & Chongqing Double Cities 6-Day  Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Chengdu begins, Chongqing ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767711463448-%E4%B8%BB%E5%9B%BE%E2%80%94%E6%88%90%E9%83%BD%E2%80%94%E6%A8%AA%E5%9B%BE-04q2MMWKiamDwGcgjVXGn3ZSuZYpTS.png", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'd48f2466-e466-4801-886c-cd28c6cc97c6',
		slug: "chongqing-highlights-magic-cityscape-day-tour",
		pageTitle: { proposed: "Chongqing Highlights & Magic Cityscape Day Tour | Korascale Travel", source: 'data.pageTitle' },
		metaDescription: { proposed: "Chongqing begins, Chongqing ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1771754676598-%E4%B8%BB%E5%9B%BE-%E9%87%8D%E5%BA%86%E5%B8%82%E5%8C%BA-%E6%A8%AA%E5%9B%BE-RG3wOzUWFTX4jHSQYUlZmKppYZJZk3.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '9b0aefcc-3604-4d5c-bcc2-0b8ee80bb621',
		slug: "grand-china-highlands-nature-18-day-journey",
		pageTitle: { proposed: "Grand China Highlands & Nature 18-Day Journey", source: 'data.pageTitle' },
		metaDescription: { proposed: "Shanghai begins · Lijiang · Shangri-La · Lhasa · Everest · Shigatse · Beijing ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1769923887089-%E4%B8%BB%E5%9B%BE-%E5%B8%83%E8%BE%BE%E6%8B%89%E5%AE%AB-%E6%A8%AA%E5%9B%BE-nUl8p9O9Z5vEKsSj7GdfgyRSebzbRu.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'eb9647df-6b38-46be-9920-9b80f27a9d2e',
		slug: "grand-china-highlights-16-day-multi-city-journey",
		pageTitle: { proposed: "Grand China Highlights 16-Day Multi-City Journey", source: 'data.pageTitle' },
		metaDescription: { proposed: "Beijing begins · Xi’an · Chengdu · Chongqing · Guilin · Shanghai ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1769921047051-%E4%B8%BB%E5%9B%BE-%E6%A1%82%E6%9E%97%E5%B1%B1%E6%B0%B4-%E6%A8%AA%E5%9B%BE-6aJddp5N5BEhJi8dKhKOYiIG2vEqPw.jpg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '4a22ea8c-15a2-4b39-b1d2-c7b3d3e32fd7',
		slug: "guangzhou-chaoshan-xiamen-cultural-loop-8-day-tour",
		pageTitle: { proposed: "Guangzhou, Chaoshan & Xiamen  Cultural Loop 8-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Guangzhou begins, Xiamen ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767336091625-%E4%B8%BB%E5%9B%BE-%E9%BC%93%E6%B5%AA%E5%B1%BF-%E6%A8%AA%E5%9B%BE-BYoPelIP7Z05GUaamn23ttGm6vw8O0.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'd2be5f8a-75a3-453a-88e6-a13c8baa70d4',
		slug: "guilin-to-yangshuo-classic-7-day-tour",
		pageTitle: { proposed: "Guilin to Yangshuo  Classic 7-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Guilin begins, Guilin ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767280379682-%E4%B8%BB%E5%9B%BE-%E6%A1%82%E6%9E%97%E5%B1%B1%E6%B0%B4-%E6%A8%AA%E5%9B%BE-cWIzMKou5RqE2x2ZWYvmqGdEZE6S1g.jpg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'fe99d869-cb67-4ba7-8791-ecdfa38c2701',
		slug: "huangshan-to-huizhou-ancient-villages-6-day-tour",
		pageTitle: { proposed: "Huangshan to Huizhou Ancient Villages 6-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Huangshan begins, Huangshan ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767340686645-%E4%B8%BB%E5%9B%BE-%E8%BF%8E%E5%AE%A2%E6%9D%BE-%E6%A8%AA%E5%9B%BE-4FOkmcw5y1HwAvY72Ou2giwRIEIiE4.jpg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'aa64bf32-d48f-4d5a-8bb7-e0e85353de5c',
		slug: "jiuzhaigou-cultural-adventure-4-day-tour",
		pageTitle: { proposed: "Jiuzhaigou Cultural & Adventure 4-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Chengdu begins, Chengdu ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767714076358-%E4%B8%BB%E5%9B%BE-%E4%B9%9D%E5%AF%A8%E6%B2%9F-%E6%A8%AA%E5%9B%BE-z8k3mNCllKHJa6CARBGLsPC7wPmzDb.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '062f363b-eabb-493c-a15b-fe769db12ac5',
		slug: "jiuzhaigou-huanglong-by-high-speed-rail-3-day-tour",
		pageTitle: { proposed: "Jiuzhaigou & Huanglong by High-Speed Rail 3-Day Tour | Korascale Travel", source: 'data.pageTitle' },
		metaDescription: { proposed: "Chengdu begins, Chengdu ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1771753923521-%E4%B8%BB%E5%9B%BE-%E4%B9%9D%E5%AF%A8%E6%B2%9F-%E6%A8%AA%E5%9B%BE-RBIWFJFZDyD8TzHhytYjCAmfndXhda.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '28ae5874-2c8f-4f88-895e-09cb45c36872',
		slug: "leshan-buddha-emei-mountain-2-day-tour",
		pageTitle: { proposed: "Leshan Buddha & Emei Mountain 2-Day Tour | Korascale Travel", source: 'data.pageTitle' },
		metaDescription: { proposed: "Chengdu begins, Chengdu ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1771753037248-%E4%B8%BB%E5%9B%BE-%E5%B3%A8%E7%9C%89%E5%B1%B1-%E6%A8%AA%E5%9B%BE-hLbMBhKWnUFPqpWmBSKQwBxKwyW5n2.png", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '43afa024-0a6b-42a4-ab24-b582778ad587',
		slug: "lhasa-holy-lakes-classic-tibet-8-day-tour",
		pageTitle: { proposed: "Lhasa & Holy Lakes  Classic Tibet 8-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Lhasa begins, Lhasa ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1768222356636-%E4%B8%BB%E5%9B%BE-%E5%B7%B4%E6%9D%BE%E6%8E%AA-%E6%A8%AA%E5%9B%BE-serMl9dPsgjQRaFlaSJXlkvu4oHyjL.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '645c7b01-6a18-4246-91b7-69f1311e9ebc',
		slug: "shanghai-suzhou-classic-dual-city-7-day-tour",
		pageTitle: { proposed: "Shanghai & Suzhou Classic Dual-City 7-Day  Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Shanghai begins, Shanghai ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767455968109-%E4%B8%BB%E5%9B%BE-%E8%8B%8F%E5%B7%9E-%E6%A8%AA%E5%9B%BE-BaUlNeqFN1L39nd7jshRCvpf2vdRix.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '743d03b7-82a9-4d72-9715-10ee9df9f231',
		slug: "siguniang-mountain-2-day-tour",
		pageTitle: { proposed: "Siguniang Mountain 2-Day Tour | Korascale Travel", source: 'data.pageTitle' },
		metaDescription: { proposed: "Chengdu begins, Chengdu ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1765962302332-%E5%9B%9B%E5%A7%91%E5%A8%98%E5%B1%B1%E5%8F%8C%E6%A1%A5%E6%B2%9F%E5%9B%9B%E5%A7%91%E5%A8%9C%E6%8E%AA2-DnmiqcpIYffSIvp9ALSTlj06LneFtk.png", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'bfd44a68-c631-4e23-950f-f93a7e9231b5',
		slug: "xian-culture-mount-hua-in-depth-4-day-tour",
		pageTitle: { proposed: "Xi'an Culture & Mount Hua  In-Depth 4-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Xi'an begins, Xi'an ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1766931010118-%E4%B8%BB%E5%9B%BE-%E8%A5%BF%E5%AE%89%E5%9F%8E%E5%A2%99-%E6%A8%AA%E5%9B%BE-NlSHPTNxeOYztmbhrzWZCqvHwWKO6I.jpg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '06f935af-8ca1-45e0-bdc3-053b94907cf2',
		slug: "xian-terracotta-warriors-tang-paradise-night-tour",
		pageTitle: { proposed: "Xi'an Terracotta Warriors & Tang Paradise Night Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Uncovering the Subterranean Scale of Ancient Empires and the Radiant Spectacle of China’s Cultural Renaissance.", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1771751385210-%E4%B8%BB%E5%9B%BE-%E5%85%B5%E9%A9%AC%E4%BF%91-%E6%A8%AA%E5%9B%BE-nsKYkQSn2Pko5A3csi3FSClT5Rr5vh.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "explore-together", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '1211dc54-4653-4bb1-a925-75fa38477919',
		slug: "xining-to-lhasa-mount-everest-tibet-grand-10-day-tour",
		pageTitle: { proposed: "Xining to Lhasa & Mount Everest  Tibet Grand 10-Day Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Xining begins, Lhasa ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767931763849-%E4%B8%BB%E5%9B%BE-%E9%9D%92%E8%97%8F%E9%93%81%E8%B7%AF-%E6%A8%AA%E5%9B%BE-KOj3Ae3UB0Luayq8Br88l9P5DGvD6r.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: 'ef87b1c3-d52a-4e8e-ade7-950e1bceadb3',
		slug: "yunnan-kunming-dali-lijiang-shangri-la-9-day-tour",
		pageTitle: { proposed: "Yunnan Kunming, Dali, Lijiang & Shangri-La 9-Day  Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Kunming begins, Shangri-La ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1768228201513-%E4%B8%BB%E5%9B%BE-%E5%A4%A7%E7%BB%8F%E5%B9%A1-%E6%A8%AA%E5%9B%BE-mRCBTRF3GbHKUl5euE15JCuIJdIECU.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	},
	{
		id: '08579f34-894b-4278-9608-a96f54d2b591',
		slug: "zhangjiajie-fenghuang-classic-7-day-dual-destination-tour",
		pageTitle: { proposed: "Zhangjiajie & Fenghuang Classic 7-Day Dual-Destination Tour", source: 'data.pageTitle' },
		metaDescription: { proposed: "Zhangjiajie begins, Zhangjiajie ends", source: 'short_description' },
		heroImageUrl: { proposed: "https://kbnup6n3k5ja0hg2.public.blob.vercel-storage.com/journeys/1767679604101-%E4%B8%BB%E5%9B%BE-%E6%AD%A6%E9%99%B5%E6%BA%90-%E6%A8%AA%E5%9B%BE-oFGPNkojecNVIpFNd7mnzy8MzDGUay.jpeg", source: 'data.heroImage' },
		journeyTypeSlug: { proposed: "deep-discovery", source: 'legacy_journey_type' },
		manualReview: false,
		reason: "active metadata backfill candidate",
	}
] as const;

export const PR_J2B3A_ACTIVE_MANIFEST_IDS = PR_J2B3A_ACTIVE_MANIFEST.map((e) => e.id);

export function assertPrJ2b3aManifestIntegrity(): void {
	if (PR_J2B3A_ACTIVE_MANIFEST.length !== 24) {
		throw new Error(`Manifest count ${PR_J2B3A_ACTIVE_MANIFEST.length} != 24`);
	}
	const ids = new Set(PR_J2B3A_ACTIVE_MANIFEST_IDS);
	if (ids.size !== 24) throw new Error('Manifest contains duplicate IDs');
	if (ids.has('e468b842-7c59-4258-8d56-8b585566be82')) {
		throw new Error('Manifest must not include e468b842');
	}
}

assertPrJ2b3aManifestIntegrity();
